//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management.Manager.Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add_Student
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public byte[] picture { get; set; }
    }
}
