//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management.Manager.Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        public string username { get; set; }
        public string passwords { get; set; }
    }
}
