//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management.Manager.Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int student_id { get; set; }
        public int course_id { get; set; }
        public Nullable<int> student_score { get; set; }
        public string descriptions { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual IF_Student IF_Student { get; set; }
    }
}
